const STORE = 'arcanum-pwa-v1';
const state = { tab: 'home', filter: 'all', search: '', data: load() };
const $ = (selector, root = document) => root.querySelector(selector);
const uid = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
function load() { try { return JSON.parse(localStorage.getItem(STORE)) || { profile: { name: 'Biblioteca', goal: 12 }, books: [] }; } catch { return { profile: { name: 'Biblioteca', goal: 12 }, books: [] }; } }
function save() { localStorage.setItem(STORE, JSON.stringify(state.data)); }
function esc(value = '') { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function cover(book, large = false) { const cls = large ? 'cover detail-cover' : 'cover'; return `<div class="${cls}">${book.cover ? `<img src="${esc(book.cover)}" alt="Capa de ${esc(book.title)}">` : esc(book.title?.slice(0, 1).toUpperCase() || 'A')}</div>`; }
function statusLabel(status) { return ({ want: 'Quero ler', reading: 'A ler', finished: 'Lido' })[status] || 'Quero ler'; }
function percent(book) { return book.pages ? Math.min(100, Math.round((book.currentPage || 0) / book.pages * 100)) : 0; }
function greeting() { const hour = new Date().getHours(); return hour < 12 ? 'Bom dia' : hour < 19 ? 'Boa tarde' : 'Boa noite'; }
function bookCard(book) { return `<button class="book" data-book="${book.id}">${cover(book)}<span class="book-info"><span class="book-title">${esc(book.title)}</span><span class="book-author">${esc(book.author || 'Autor desconhecido')}</span><span class="status">${statusLabel(book.status)}</span></span><span><span class="book-meta">${book.currentPage || 0}/${book.pages || '—'}</span><span class="book-progress"><span style="width:${percent(book)}%"></span></span></span></button>`; }
function home() { const books = state.data.books; const reading = books.filter(b => b.status === 'reading'); const finished = books.filter(b => b.status === 'finished'); const pages = books.reduce((sum, b) => sum + (b.currentPage || 0), 0); const current = reading[0]; return `<section class="page-head"><div><p class="eyebrow">${greeting()}, ${esc(state.data.profile.name)}</p><h1 class="page-title">O teu Arcanum</h1></div><button class="add-button" aria-label="Adicionar livro" data-action="add">+</button></section>${current ? `<article class="hero"><p class="eyebrow">A ler agora</p><h2>${esc(current.title)}</h2><p>${esc(current.author || 'Autor desconhecido')} · ${current.currentPage || 0} de ${current.pages || '—'} páginas</p><div class="progress"><span style="width:${percent(current)}%"></span></div></article>` : `<div class="hero"><p class="eyebrow">A tua biblioteca</p><h2>Pronto para a próxima história?</h2><p>Adiciona um livro e começa a acompanhar a tua leitura.</p></div>`}<div class="stats"><div class="stat"><strong>${books.length}</strong><small>na biblioteca</small></div><div class="stat"><strong>${finished.length}</strong><small>livros lidos</small></div><div class="stat"><strong>${pages}</strong><small>páginas lidas</small></div></div><h3 class="section-title">Continua a ler</h3>${reading.length ? `<div class="book-list">${reading.map(bookCard).join('')}</div>` : `<div class="empty"><b>Sem leituras em curso</b>Quando começares, o livro aparece aqui.</div>`}`; }
function library() { const filtered = state.data.books.filter(b => (state.filter === 'all' || b.status === state.filter) && `${b.title} ${b.author}`.toLocaleLowerCase().includes(state.search.toLocaleLowerCase())); return `<section class="page-head"><div><p class="eyebrow">Coleção</p><h1 class="page-title">Biblioteca</h1></div><button class="add-button" aria-label="Adicionar livro" data-action="add">+</button></section><input class="search" id="search" value="${esc(state.search)}" placeholder="Pesquisar título ou autor"><div class="filters">${[['all','Todos'],['reading','A ler'],['want','Quero ler'],['finished','Lidos']].map(([id,label]) => `<button class="chip ${state.filter === id ? 'active' : ''}" data-filter="${id}">${label}</button>`).join('')}</div>${filtered.length ? `<div class="book-list">${filtered.map(bookCard).join('')}</div>` : `<div class="empty"><b>Não há livros aqui</b>Adiciona o primeiro à tua biblioteca.</div>`}`; }
function statistics() { const books = state.data.books, complete = books.filter(b => b.status === 'finished'), totalPages = books.reduce((sum, b) => sum + (b.currentPage || 0), 0), genres = {}; books.forEach(b => (b.genres || '').split(',').map(x => x.trim()).filter(Boolean).forEach(g => genres[g] = (genres[g] || 0) + 1)); const top = Object.entries(genres).sort((a,b)=>b[1]-a[1]).slice(0,4); return `<section class="page-head"><div><p class="eyebrow">A tua atividade</p><h1 class="page-title">Estatísticas</h1></div></section><div class="stats"><div class="stat"><strong>${complete.length}</strong><small>livros terminados</small></div><div class="stat"><strong>${totalPages}</strong><small>páginas registadas</small></div><div class="stat"><strong>${books.filter(b=>b.status==='reading').length}</strong><small>em curso</small></div></div><h3 class="section-title">Meta anual</h3><article class="hero"><h2>${complete.length} de ${state.data.profile.goal || 12} livros</h2><p>Continua assim — cada página conta.</p><div class="progress"><span style="width:${Math.min(100, Math.round(complete.length / (state.data.profile.goal || 12) * 100))}%"></span></div></article><h3 class="section-title">Géneros mais lidos</h3>${top.length ? `<div class="book-list">${top.map(([genre,count]) => `<div class="book"><span class="cover">✦</span><span class="book-info"><span class="book-title">${esc(genre)}</span><span class="book-author">${count} ${count === 1 ? 'livro' : 'livros'}</span></span></div>`).join('')}</div>` : `<div class="empty"><b>Ainda sem dados</b>Adiciona géneros aos teus livros.</div>`}`; }
function settings() { return `<section class="page-head"><div><p class="eyebrow">Preferências</p><h1 class="page-title">Definições</h1></div></section><article class="hero"><p class="eyebrow">A tua biblioteca</p><h2>${esc(state.data.profile.name)}</h2><p>Os dados ficam guardados apenas neste dispositivo.</p></article><div class="setting"><div><b>Exportar biblioteca</b><p>Guarda uma cópia em formato JSON.</p></div><button class="text-button" data-action="export">Exportar</button></div><div class="setting"><div><b>Importar biblioteca</b><p>Restaura uma cópia exportada.</p></div><label class="text-button">Importar<input id="import" type="file" accept="application/json" hidden></label></div><div class="setting"><div><b>Instalar no iPhone</b><p>No Safari, toca em Partilhar e em “Adicionar ao ecrã principal”.</p></div></div><div class="actions" style="justify-content:flex-start"><button class="secondary" data-action="profile">Editar perfil e meta</button></div>`; }
function render() { const pages = { home, library, statistics, settings }; $('#app').innerHTML = `${pages[state.tab]()}<nav class="bottom-nav">${[['home','⌂','Início'],['library','▤','Biblioteca'],['statistics','◔','Estatísticas'],['settings','⚙','Definições']].map(([id,icon,label])=>`<button class="nav-item ${state.tab===id?'active':''}" data-tab="${id}"><span>${icon}</span>${label}</button>`).join('')}</nav>`; }
function modal(content) { $('#modal-root').innerHTML = `<div class="modal-layer"><section class="modal">${content}</section></div>`; }
function closeModal() { $('#modal-root').innerHTML = ''; }
function bookForm(book = {}) { modal(`<div class="modal-head"><h2>${book.id ? 'Editar livro' : 'Novo livro'}</h2><button class="close" data-close>×</button></div><form id="book-form"><div class="form-grid"><label class="field">Título<input name="title" required value="${esc(book.title)}" placeholder="Título do livro"></label><label class="field">Autor<input name="author" value="${esc(book.author)}" placeholder="Nome do autor"></label><label class="field">Estado<select name="status">${[['want','Quero ler'],['reading','A ler'],['finished','Lido']].map(([v,l])=>`<option value="${v}" ${book.status===v?'selected':''}>${l}</option>`).join('')}</select></label><label class="field">Páginas<input name="pages" type="number" min="1" value="${book.pages || ''}" inputmode="numeric"></label><label class="field">Página atual<input name="currentPage" type="number" min="0" value="${book.currentPage || ''}" inputmode="numeric"></label><label class="field">Géneros<input name="genres" value="${esc(book.genres)}" placeholder="Fantasia, Romance..."></label></div><label class="field">URL da capa<input name="cover" type="url" value="${esc(book.cover)}" placeholder="https://..."></label><label class="field">Notas<textarea name="notes" placeholder="As tuas notas">${esc(book.notes)}</textarea></label><div class="actions">${book.id ? `<button class="danger" type="button" data-delete="${book.id}">Apagar</button>` : ''}<button class="secondary" type="button" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`); $('#book-form').addEventListener('submit', e => { e.preventDefault(); const values = Object.fromEntries(new FormData(e.target)); const next = { id: book.id || uid(), ...values, pages: Number(values.pages) || 0, currentPage: Number(values.currentPage) || 0, createdAt: book.createdAt || new Date().toISOString() }; if (next.status === 'finished' && next.pages) next.currentPage = next.pages; if (book.id) state.data.books = state.data.books.map(b => b.id === book.id ? next : b); else state.data.books.unshift(next); save(); closeModal(); render(); }); }
function detail(id) { const book = state.data.books.find(b => b.id === id); if (!book) return; modal(`<div class="modal-head"><span></span><button class="close" data-close>×</button></div>${cover(book,true)}<div class="detail-heading"><h2>${esc(book.title)}</h2><p>${esc(book.author || 'Autor desconhecido')}</p></div><div class="detail-grid"><div>Estado<strong>${statusLabel(book.status)}</strong></div><div>Progresso<strong>${book.currentPage || 0} / ${book.pages || '—'}</strong></div></div>${book.notes ? `<p class="book-meta" style="line-height:1.5">${esc(book.notes)}</p>` : ''}<div class="actions"><button class="secondary" data-close>Fechar</button><button class="primary" data-edit="${book.id}">Editar</button></div>`); }
function profileForm() { const p = state.data.profile; modal(`<div class="modal-head"><h2>Perfil</h2><button class="close" data-close>×</button></div><form id="profile-form"><label class="field">Nome da biblioteca<input name="name" required value="${esc(p.name)}"></label><label class="field">Meta anual de livros<input name="goal" required min="1" type="number" inputmode="numeric" value="${p.goal || 12}"></label><div class="actions"><button class="secondary" type="button" data-close>Cancelar</button><button class="primary">Guardar</button></div></form>`); $('#profile-form').addEventListener('submit', e => { e.preventDefault(); const v = Object.fromEntries(new FormData(e.target)); state.data.profile = { name:v.name, goal:Number(v.goal)||12 }; save(); closeModal(); render(); }); }
document.addEventListener('click', e => { const tab = e.target.closest('[data-tab]'); if (tab) { state.tab = tab.dataset.tab; render(); } const filter = e.target.closest('[data-filter]'); if (filter) { state.filter = filter.dataset.filter; render(); } const book = e.target.closest('[data-book]'); if (book) detail(book.dataset.book); if (e.target.closest('[data-action="add"]')) bookForm(); if (e.target.closest('[data-close]')) closeModal(); const edit = e.target.closest('[data-edit]'); if (edit) bookForm(state.data.books.find(b=>b.id===edit.dataset.edit)); const remove = e.target.closest('[data-delete]'); if (remove) { const target = state.data.books.find(b=>b.id === remove.dataset.delete); if (target && confirm(`Apagar “${target.title}”?`)) { state.data.books = state.data.books.filter(b=>b.id!==target.id); save(); closeModal(); render(); } } if (e.target.closest('[data-action="profile"]')) profileForm(); if (e.target.closest('[data-action="export"]')) { const blob = new Blob([JSON.stringify(state.data,null,2)], {type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='arcanum-biblioteca.json'; a.click(); URL.revokeObjectURL(a.href); } });
document.addEventListener('input', e => { if (e.target.id === 'search') { state.search = e.target.value; render(); $('#search')?.focus(); } });
document.addEventListener('change', e => { if (e.target.id === 'import') { const reader = new FileReader(); reader.onload = () => { try { const parsed = JSON.parse(reader.result); if (!Array.isArray(parsed.books) || !parsed.profile) throw new Error(); state.data = parsed; save(); render(); alert('Biblioteca importada.'); } catch { alert('Este ficheiro não parece ser uma exportação do Arcanum.'); } }; reader.readAsText(e.target.files[0]); } });
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js'));
render();
